import type { Metadata } from "next"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import AppLayout from "@/components/AppLayout"
import ThemeProviderCR from "@/app/themeProvider"
import { Box } from "@mui/material"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headerHeight = 64 // Header height in px
  return (
    <html lang="en">
      <body style={{ backgroundColor: "white" }}>
        <ThemeProviderCR>
          <AppRouterCacheProvider>
            <AppLayout headerHeight={headerHeight} />
            <Box bgcolor={"white"} marginTop={`${headerHeight}px`} p={2}>
              {children}
            </Box>
          </AppRouterCacheProvider>
        </ThemeProviderCR>
      </body>
    </html>
  )
}
