basePath: /
definitions:
  model.Dish:
    properties:
      id:
        description: 料理ID
        type: string
      img:
        description: 画像URL
        type: string
      nameEn:
        description: 英語名
        type: string
      nameJa:
        description: 日本語名
        type: string
      price:
        description: 価格
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for searching dishes
  title: CookOrder API
  version: "1.0"
paths:
  /dishes:
    get:
      description: 料理一覧を取得します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Dish'
            type: array
      summary: 料理一覧取得
      tags:
      - dishes
    post:
      consumes:
      - application/json
      description: 新しい料理を登録します
      parameters:
      - description: Dish情報
        in: body
        name: dish
        required: true
        schema:
          $ref: '#/definitions/model.Dish'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Dish'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 新しい料理を登録
      tags:
      - dishes
  /dishes/search:
    get:
      description: 日本語名・英語名で料理を部分一致検索します
      parameters:
      - description: 日本語名で部分一致検索
        in: query
        name: nameJa
        type: string
      - description: 英語名で部分一致検索
        in: query
        name: nameEn
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Dish'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 料理検索
      tags:
      - dishes
swagger: "2.0"
