// This file is generated by foodGenerate.ts. Do not edit it manually.
// This file contains a list of food products with random names and prices.
// I will delete this file after implementing the food generation feature use BE api.

import { dishList } from "./dishNames"

const products = []

for (let i = 1; i <= 99; i++) {
  const dish = dishList[i]
  products.push({
    id: i,
    name: dish.name,
    option: dish.tag,
    price: Math.floor(Math.random() * 2000) + 500, // 500〜2500円のランダム価格
    imageUrl: "https://www.h-maruko.co.jp/images/material/00384.jpg",
  })
}

export const productsData = products
